"""empty message

Revision ID: fd8dadd33773
Revises: 0a8d80614d64
Create Date: 2021-03-31 17:04:35.582182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8dadd33773'
down_revision = '0a8d80614d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'name')
    # ### end Alembic commands ###
